enableTelemetry: false

nodeLinker: pnp

packageExtensions:
  "@nextui-org/calendar@*":
    peerDependencies:
      "framer-motion": "*"
  "@nextui-org/date-picker@*":
    peerDependencies:
      "framer-motion": "*"
  "@nextui-org/use-aria-menu@*":
    peerDependencies:
      "react-dom": "*"
  "@nextui-org/system@*":
    dependencies:
      "framer-motion": "*"
  "@nextui-org/system-rsc@*":
    dependencies:
      "@nextui-org/theme": "*"
  "@nextui-org/theme@*":
    dependencies:
      color: "*"
      lodash: "*"
      "lodash.omit": "*"
      tailwindcss: "*"


yarnPath: .yarn/releases/yarn-4.5.0.cjs
